### PR TITLE
add client info header for postgrest-go

### LINKED ISSUE #16: X-Client-Info header
we're rolling out a header similar to Stripe's App-Data in all of the client libs so issues can be debugged more easily between the client and the backend

the javascript libs are done already: https://github.com/supabase/supabase-js/pull/238

the format is: `X-Client-Info: supabase-js/1.11.0`

for client libs that wrap others (like how supabase-js wraps gotrue-js) we allow the wrapper lib to **overwrite** the wrapped lib's header (given that we can infer the gotrue-js version based on which supabase-js was used to make the call)

any help with rolling this out here would be incredible

### PR DESCRIPTION
**Pull request by bariqhibat**
Signed-off-by: Bariq <bariqhibat@gmail.com>

Resolves #16

### CODE REVIEW

**Comment by bariqhibat** [comment]
> Thanks for help 💯 Executing git is may not work in production. We can do this like js library. Set version constant in the client. And use it in X-Client-Info.

Yeah this is particularly a hacky way to do it haha. So that means we hardcoded it for each releases is it?

**Comment by yusufpapurcu** [comment]
Hardcoding is a more safe way to do it. Also who wants running git in every initialization 😆

**Comment by bariqhibat** [comment]
> Hardcoding is a more safe way to do it. Also who wants running git in every initialization 😆

Okie just made the change!

**Comment by yusufpapurcu** [comment]
Excellent 🚀 

Long live hardcoding 😄

**Pull request merged**
